### ISSUE TITLE
Too many open files Pyro4.53

### ISSUE THREAD

**Issue by pudding222** [irmen/Pyro4#146]
When processing a large number of requests using the Pyro version 4.53 or 4.50 I get the error "Too many open files" on a Ubuntu 14 machine, this is the same if using Python 2.7 or Python3.

If I downgrade to Pyro 4.47 then the problem does not appear to be there. 
If I change the parameter "numberOfThreads" to 1 to run it single threaded the problem doesnt appear.

If you run the program below it will end normally using Pyro4.47 printing the "ENDING". Running on the two newer versions a crash happens stating:

OSError: [Errno 24] Too many open files

Here is the code:

```python
import sys
import Pyro4
import time
import threading
import subprocess
import os

name = "TESTING" ## Part of the Pyro URI
host="127.0.0.1" ## ip to bind the sPyro server to
port=9991 ## Port to bind the Pyro server to
pid=os.getpid() ## PID of the python program running so that we can get a list of the 
stop_event= threading.Event() ## Since were starting a number of daemon threads, this is used to tell those threads to stop.


def lsof(pidOfServer):
    stdin=subprocess.PIPE
    stdout=subprocess.PIPE
    stderr=subprocess.PIPE
    while not stop_event.is_set():
        cmd="lsof -p %s | wc -l"%pidOfServer
        p = subprocess.Popen([cmd], stdin=stdin, stdout=stdout, stderr=stderr,shell=True)
        response="%s"%p.communicate()[0].strip()
        print("Number of open files for server: %s"%response)

@Pyro4.expose
class GreetingMaker(object):
    def get_fortune(self, name):        
        return "Hello, {0}. Here is your fortune message:\n" \
               "Behold the warranty -- the bold print giveth and the fine print taketh away.".format(name)

def server(host,port):
    daemon = Pyro4.Daemon(host=host, port=port)
    uri = daemon.register(GreetingMaker,objectId="TESTING")
    print("Ready")
    try:
        daemon.requestLoop()
    except Exception  as e:
        print("Error in server: %s"%e)
        stop_event.set()
        raise

def myfunc(host,port,name):
    with Pyro4.Proxy("PYRO:%s@%s:%s"%(name,host,port)) as greeting_maker:
        greeting_maker.get_fortune(name)   # call method normally
    
def client():
    requestsProcessed=0 ## Count of the number of attempts we have to the server
    numberOfTimes=1000 ## Number of times to loop
    numberOfThreads=15 ## Number of threads to start per loop
    for i in range(numberOfTimes):
        threads=[]
        for i in range(numberOfThreads):
            thread = threading.Thread(target=myfunc, args=(host,port,name))
            thread.start()
            threads.append(thread)
        for thread in threads:
            thread.join()
        requestsProcessed+=numberOfThreads*numberOfTimes
        #print("Processed %s requests"%requestsProcessed)

if __name__=="__main__":
    
    lsofThread = threading.Thread(target=lsof, args=(pid,))
    lsofThread.daemon = True
    lsofThread.start() ## Background daemon to monitoring the number of open files for this pid

    serverThread = threading.Thread(target=server, args=(host,port))
    serverThread.daemon = True
    serverThread.start() ## Background daemon to start the Pyro server up

    client()
    print("SLEEPING")
    time.sleep(2)
    if not stop_event.is_set(): ## attempt to terminate the background threads
        stop_event.set()
    print("ENDING")
```

**Comment by irmen** [comment]
Please provide the full stacktrace of the OSError as well. Where does it occur?

**Comment by pudding222** [comment]
Im using Python 2.7.6 or Python 3.4.3 with Ubuntu 14 LTS. 
I dont think im using serpent but its version 1.16 selectors34 version 1.1

"ulimit -n" gives me 1024 
"ulimit" give unlimited. 

The trace back is as follows:

```python
Number of open files for server: 1035
Exception in thread Thread-10240:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "PClient.py", line 45, in myfunc
    greeting_maker.get_fortune(name)   # call method normally
  File "./Pyro4/core.py", line 262, in __getattr__
    self._pyroGetMetadata()
  File "./Pyro4/core.py", line 569, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "./Pyro4/core.py", line 521, in __pyroCreateConnection
    raise ce
CommunicationError: cannot connect: [Errno 24] Too many open files
```

**Comment by irmen** [comment]
I've installed Xubuntu 14 LTS (14.04.5) directly from the iso and didn't run any updates. Then I tried your test program again. I'm sorry, but I am still unable to reproduce any problem with it- it runs just fine. With python 2 and with python 3.
My configuration:
- xubuntu 14.04.5 LTS (Jul 13 2016)
- system default python 2.7.6 (Jun 22 2015) and python 3.4.3 (Nov 17 2016)
- unrelated, but still: serpent 1.16 and selectors34 1.1
- default Pyro4 and shell configs.

It really is something about your system or software configuration on your end.

Let me suggest to
- run it from a fresh virtualenv
- check your configuration settings (both linux/shell and Pyro)
- upgrade to a newer linux distro version (perhaps Unbuntu 16 LTS, or perhaps even something else entirely)
- try updating your python versions

It's impossible for me now to investigate this. It really does not seem to be a problem in Pyro4 itself.

**Comment by pudding222** [comment]
I tried this again using the a new VM with the stock installation of Ubuntu14 and a new still found the problem. I did however notice that on the machine I tried it on (which is slower) that the time it took longer to crash, I had to adjust the ```numberOfTimes=1000``` variable to be 5000. Can I ask did the message:

"Number of open files for server: X" keep increasing as it was run on the setup you had? If so depending on the speed of the underling machine you may need to increase the "numberOfTimes" variable.


Just for the record:
* ubuntu 14.04.5
* Python 2.7.6
* Pyro 4.53
* serpent 1.16 and selectors34 1.1

Im just trying the same thing on a stock installation of Ubuntu 16


I did some googling and found this:

[link](https://github.com/dln/python-libuuid/issues/1) and was wondering if this would be affecting it?

**Comment by irmen** [comment]
What number of CPUs does your machine have that shows the problem? 
Also I really hope the uuid1 thing you found has been solved by now, the article is from 5 years ago.

Anyway. I would still like to ask you to try to zoom in further on what is causing the issue at your end. There's now simply way too little information to go with.

**Comment by pudding222** [comment]
Firstly thanks for helping me out with this issue.
Ive had a bit more of a testing session today and can confirm that the issue isnt present on Ubuntu16 and only there on Ubutun14. 
Looking at the lsof for the PID that has the issue, the  following is the dump as the code is running:

```lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
python  6249 root  cwd    DIR   0,27        0      0 /media/sf_linux_shared
python  6249 root  rtd    DIR    8,1     4096      2 /
python  6249 root  txt    REG    8,1  3341384  49432 /tmp/dan/venv/bin/python
python  6249 root  mem    REG    8,1   109232 269000 /usr/lib/python2.7/lib-dynload/datetime.x86_64-linux-gnu.so
python  6249 root  mem    REG    8,1    54064 269011 /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
python  6249 root  mem    REG    8,1    18936   5881 /lib/x86_64-linux-gnu/libuuid.so.1.3.0
python  6249 root  mem    REG    8,1    20664 269006 /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
python  6249 root  mem    REG    8,1    30944 143981 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
python  6249 root  mem    REG    8,1   136232 269035 /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
python  6249 root  mem    REG    8,1  1934624   6025 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
python  6249 root  mem    REG    8,1   387272   6354 /lib/x86_64-linux-gnu/libssl.so.1.0.0
python  6249 root  mem    REG    8,1    38480 269022 /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
python  6249 root  mem    REG    8,1  7216688 140826 /usr/lib/locale/locale-archive
python  6249 root  mem    REG    8,1  1071552   6047 /lib/x86_64-linux-gnu/libm-2.19.so
python  6249 root  mem    REG    8,1   100728   6160 /lib/x86_64-linux-gnu/libz.so.1.2.8
python  6249 root  mem    REG    8,1    10680   6152 /lib/x86_64-linux-gnu/libutil-2.19.so
python  6249 root  mem    REG    8,1    14664   6014 /lib/x86_64-linux-gnu/libdl-2.19.so
python  6249 root  mem    REG    8,1  1840928   5997 /lib/x86_64-linux-gnu/libc-2.19.so
python  6249 root  mem    REG    8,1   141574   6117 /lib/x86_64-linux-gnu/libpthread-2.19.so
python  6249 root  mem    REG    8,1   149120   5973 /lib/x86_64-linux-gnu/ld-2.19.so
python  6249 root    0u   CHR  136,1      0t0      4 /dev/pts/1
python  6249 root    1u   CHR  136,1      0t0      4 /dev/pts/1
python  6249 root    2u   CHR  136,1      0t0      4 /dev/pts/1
python  6249 root    3u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    4u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    5u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    6u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    7u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    8u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root    9u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   10u  IPv4 275672      0t0    TCP localhost:9991 (LISTEN)
python  6249 root   11u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   12u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   13u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   14u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   15u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   16u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   17u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   18u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   19u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   20u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   21u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   22u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   23u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   24u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   25u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   26u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   27u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   28u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   29u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   30u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   31u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   32u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   33u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   34u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   35u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   36u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   37u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   38u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   39u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   40u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   41u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   42u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   43u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   44u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   45u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   46u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   47u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   48u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   49u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   50u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   51u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   52u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   53u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   54u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   55u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   56u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   57u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   58u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   59u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   60u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   61u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   62u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   63u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   64u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   65u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   66u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   67u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   68u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   69u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   70u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   71u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   72u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   73u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   74u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   75u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   76u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   77u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   78u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   79u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   80u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   81u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   82u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   83u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   84u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   85u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   86u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   87u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   88u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   89u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   90u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   91u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   92u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   93u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   94u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   95u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   96u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   97u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   98u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root   99u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  100u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  101u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  102u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  103u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  104u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  105u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  106u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  107u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  108u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  109u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  110u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  111u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  112u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  113u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  114u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  115u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  116u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  117u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  118u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  119u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  120u  IPv4 315420      0t0    TCP localhost:40424->localhost:9991 (ESTABLISHED)
python  6249 root  121u  IPv4 315114      0t0    TCP localhost:9991->localhost:40424 (ESTABLISHED)
python  6249 root  124u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  126u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  129u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  130u   REG    8,1       56 316732 /var/lib/libuuid/clock.txt
python  6249 root  133r  FIFO   0,10      0t0 315406 pipe
python  6249 root  136r  FIFO   0,10      0t0 315407 pipe
```

As the code is running the number of instances of "/var/lib/libuuid/clock.txt" keeps increasing and doesnt seem to go down.
im going to try this again tonight on another ubuntu 14 machine to verify the enviroment.

**Comment by irmen** [comment]
Thank you, now we are getting somewhere!
Somehow that weird uuid1 bug *is* a thing on your system!
What is weird about htis, why am I not seeing it? Something must be different. 
Do you have the python-libuuid package installed by any chance? From what I can tell, that one may expose this particular problem. I don't have it. As far as I can tell the version from the standard library doesn't contain any reference to ``/var/lib/libuuid/clock.txt``  so *what is* creating this on your system?

**Comment by irmen** [comment]
Okay, on closer inspection, python's ``uuid`` module uses ctypes to interface with c libraries if they are available. So i guess it DOES call into the libuuid.so library.  Why I'm not seeing the problem remains a mistery to me right now. The thing that I can still try is to install 64-bit xubuntu instead (I'm using 32 bits right now) and/or test this on my OSX machine as well

**Comment by irmen** [comment]
I don't have more time and energy to dive into possible low level resource leaks in the uuid1 library function so I've opted to completely avoid the issue: I've changed the remaining places where Pyro called ``uuid1()`` to a call to ``uuid4()`` instead (Pyro4 already used this for some other things, now it's using them everywhere). 
Can you check if the current master branch version of Pyro4 solves the problem on your end?

**Comment by pudding222** [comment]
Just to updated I did try it on yet another VM on another HOST and that did have the same issue and im really confused how come im seeing it and your not. I did check out the UUID1 generation and noticed the c_types so im assumming for whatever reason were both not using the same methods.

Anyhow the fixes that you have done to use UUID4 instead of UUID1 seem to have addressed the problem im seeing and the ``` lsof ``` is now stable and does not increase.

Thanks for looking into this! Ill close the issue assumming that you will generate another release.

**Comment by irmen** [comment]
Yeah I have no idea what could cause this on your systems. You are the first to ever notice the issue as well. Even with the "uuid1 torture test" found below, I could not get any of my systems to expose the resource leak; they're all generating hundreds of thousands of uuids without issues. 
You can try the below code to see if it crashes on your machines.

And yes, the uuid1->uuid4 change will be part of the next Pyro4 release which will appear shortly (coming weekend or so)

```
import uuid
import threading
import os

class TestThread(threading.Thread):
    def run(self):
        name = threading.current_thread().name
        pid = os.getpid()
        i = 0
        while True:
            i += 1
            guid = uuid.uuid1()
            if i % 1000 == 0:
                print(pid, name, guid, i)


if __name__ == "__main__":
    print("TEST UUID")
    threads = []
    for _ in range(4):
        thread = TestThread()
        threads.append(thread)
        thread.start()

    threads[0].join()

```

**Comment by irmen** [comment]
new release with the fix is available.
