### ISSUE TITLE
Better error messages?

### ISSUE THREAD

**Issue by krey** [irmen/Pyro4#177]
If my client uses a serializer that the nameserver doesn't accept (eg. pickle by default), all I get is an error that nameserver not found. This was very difficult to debug.
Please consider more helpful error messages.

**Comment by irmen** [comment]
The error message is clear enough as it is, IMO:

```
>>> import Pyro4
>>> Pyro4.locateNs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Pyro4' has no attribute 'locateNs'
>>> Pyro4.locateNS()
Traceback (most recent call last):
  File "D:\PROJECTS\Pyro4\src\Pyro4\core.py", line 1900, in _locateNS
    proxy._pyroBind()
  File "D:\PROJECTS\Pyro4\src\Pyro4\core.py", line 403, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "D:\PROJECTS\Pyro4\src\Pyro4\core.py", line 552, in __pyroCreateConnection
    raise errors.CommunicationError(error)
Pyro4.errors.CommunicationError: connection to ('localhost', 9090) rejected: message used serializer that is not accepted: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PROJECTS\Pyro4\src\Pyro4\core.py", line 1907, in _locateNS
    raise e
Pyro4.errors.NamingError: Failed to locate the nameserver
>>>

```

See the nested exception message: " connection to ('localhost', 9090) rejected: message used serializer that is not accepted: 1"   

The above is a feature only provided in Python 3 though so if you're still using Python 2.x, you'll have to upgrade to be able to see the chained exceptions. Alternatively, enable Pyro's logging and you'll see the reason a connection is refused in the logfile:
```

[2017-06-26 19:47:19.687,Pyro4.core,DEBUG] connecting to PYRO:Pyro.NameServer@localhost:9090
[2017-06-26 19:47:19.690,Pyro4.core,ERROR] connection to ('localhost', 9090) rejected: message used serializer that is not accepted: 1

```

I'm wondering why this was difficult for you to debug? How do you think this should be improved?
