### ISSUE TITLE
How to expose a staticmethod?

### ISSUE THREAD

**Issue by jcea** [irmen/Pyro4#185]
I miss the mailing list! :-).

When I do this:

```
class dummy:
    @Pyro4.expose
    @staticmethod
    def add(a, b):
        return a+b
```
I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in dummy
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 946, in expose
    if util.is_private_attribute(method_or_class.__name__):
AttributeError: 'staticmethod' object has no attribute '__name__'
```

How should I expose an static method?

Thanks.

**Comment by irmen** [comment]
Hmm, for now I suggest wrapping the call to the static method in a regular method

```
class Dummy:
    @Pyro4.expose
    def call_my_static(self, a, b):
        return Dummy.add(a, b)

    @staticmethod
    def add(a, b):
        return a+b

```

**Comment by irmen** [comment]
It seems it may be a little bug in the expose decorator because if you put that on the *class* instead of the method, it works fine and it exposes static and classmethods just fine
