### ISSUE TITLE
Hang up if there is any exception occurred on the remote

### ISSUE THREAD

**Issue by weyou** [irmen/Pyro4#27]
``` python
>>> import Pyro4
>>> Pyro4.config.SERIALIZER = 'pickle'
>>> Pyro4.config.SERIALIZERS_ACCEPTED.add('pickle')
>>> p = Pyro4.Proxy("PYRONAME:test.controller")
>>> p.testcall('abc')
```

The parameter is invalid and will cause an exception on remote object.
But the local testcall() will always hang up until press the "Ctrl-C", it shows the traceback like this:

``` python
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/testkit/env/local/lib/python2.7/site-packages/Pyro4/core.py", line 160, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/testkit/env/local/lib/python2.7/site-packages/Pyro4/core.py", line 306, in _pyroInvoke
    msg = Message.recv(self._pyroConnection, [Pyro4.message.MSG_RESULT])
  File "/home/testkit/env/local/lib/python2.7/site-packages/Pyro4/message.py", line 156, in recv
    msg = cls.from_header(connection.recv(cls.header_size))
  File "/home/testkit/env/local/lib/python2.7/site-packages/Pyro4/socketutil.py", line 446, in recv
    return receiveData(self.sock, size)
  File "/home/testkit/env/local/lib/python2.7/site-packages/Pyro4/socketutil.py", line 152, in receiveData
    data=sock.recv(size, socket.MSG_WAITALL)
KeyboardInterrupt

```
## Other information

Pyro version 4.22
Python 2.7
Platform: Ubuntu(Local) and Raspbian(Remote)

**Comment by ODYCCEUS-EU** [comment]
Same thing happens to me. Minimal example is to simply call a remote object with invalid arguments. In my case, a list instead of a string.
